apiVersion: v1
kind: Secret
metadata:
  name: name
  labels:
    component: {{ .Values.secret.component}}
    project: {{ .Values.secret.project}}
    tier: {{ .Values.secret.tier}}
type: Opaque
data:
  AMQP_USER: "cm9ib3Nob3A="
  AMQP_PASS: "cm9ib3Nob3AxMjM="